config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  devise_for :parents, controllers: { sessions: 'authentication/parent_sessions' }
  devise_for :teachers, controllers: { sessions: 'authentication/teacher_sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  concern :public_routes do
    get '/', to: 'public/home#index'

    resources :courses, only: :show
  end

  authenticated :teacher do
    namespace :teacher do
      get '/', to: 'home#index', as: 'home'

      get  '/levels', to: 'levels#manage', as: 'levels'
      post '/levels', to: 'levels#update', as: 'update_levels'

      resources :semesters do
        post 'act/:transition(/:lottery_id)', action: 'act', as: 'act'

        get  :lottery

        # resetting priorities
        collection do
          get 'priorities/manage'
          post 'priorities/reset'
        end
      end

      resources :special_events,              except: :index

      resources :courses,                     except: :index

      resources :sections,                    except: :index do
        get 'attendance' # download the attendance record
      end

      # TODO: is this still in use?
      resources :sections, as: :event_groups, except: :index

      resources :events,                      except: :index do
        resource :rollcall, only: :show
      end

      resources :rollcalls, only: [:create, :update]

      resources :parents,   only: [:index, :destroy] do
        collection do
          get 'search'
        end

        resources :students, only: [:index, :new], controller: 'parents/students'
        resource :profile,   only: [:show, :edit, :update]
      end

      resources :students, except: [:new] do
        collection do
          get 'search_form'
          get 'search'
          get 'name'
        end

        resource :ballot,    except: [:show, :index] do
          get :courses, as: 'courses'
        end

        resource :registree, except: [:show, :index] do
          get :courses, as: 'courses'
        end
      end

      get '*path', to: 'errors#not_found'
    end
  end

  authenticated :parent do
    namespace :parent do
      get '/',        to: 'home#index',    as: 'home'
      get 'catalog',  to: 'home#catalog',  as: 'catalog'
      get 'schedule', to: 'home#schedule', as: 'schedule'
      get 'levels',   to: 'home#levels',   as: 'levels'

      resources :special_events, only: [:index] do
        resource :special_registree, except: [:index, :new, :edit]
      end

      resource :profile, only: [:show, :create, :update]

      resources :students do
        get 'schedule', on: :member

        resource :ballot, except: [:show, :index] do
          get :courses, as: 'courses'
        end

        resource :registree, except: [:show, :index] do
          get :courses, as: 'courses'
        end
      end

      get '*path', to: 'errors#not_found'
    end
  end

  unauthenticated concern: :public_routes do
    root to: 'public/home#index'

    devise_scope :teacher do
      scope :teacher do
        root        to: 'authentication/teacher_sessions#new'
        get '*all', to: 'authentication/teacher_sessions#new'
      end
    end

    devise_scope :parent do
      scope :parent do
        root        to: 'authentication/parent_sessions#new'
        get '*all', to: 'authentication/parent_sessions#new'
      end
    end
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/teacher/ballots_controller.rb
class Teacher::BallotsController < Teacher::BaseController
  include BallotsControllable
  self.role = :teacher
end

app/controllers/teacher/base_controller.rb
class Teacher::BaseController < ApplicationController
  self.role = :teacher
end

app/controllers/teacher/courses_controller.rb
class Teacher::CoursesController < Teacher::BaseController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses/1
  def show
    @enrollment = EnrollmentHelper.section_enrollment @course
  end

  # GET /courses/new
  def new
    @course = Course.new(semester_id: params[:semester_id])
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to teacher_semester_path(@course.semester), notice: 'Course was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /courses/1
  def update
    if @course.update(course_params)
      redirect_to teacher_course_path(@course), notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /courses/1
  def destroy
    @course.destroy
    redirect_to teacher_courses_url, notice: 'Course was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def course_params
    params.fetch(:course, {}).permit(:name, :level_id, :capacity, :semester_id, :overview)
  end
end

app/controllers/teacher/errors_controller.rb
class Teacher::ErrorsController < ErrorsController
end

app/controllers/teacher/events_controller.rb
class Teacher::EventsController < Teacher::BaseController
  before_action :set_event, except: [:new, :create, :index]
  before_action :set_rollcall, only: [:rollcall, :create_rollcall, :update_rollcall]

  def rollcall
  end

  def create_rollcall
    @rollcall.attendance = rollcall_params[:attendance]

    if @rollcall.save
      redirect_to teacher_section_path(@rollcall.event.section), notice: "Attendance record saved."
    else
      flash[:alert] = "Attendance record could not be saved, please try again."
      render :rollcall
    end
  end

  def update_rollcall
    if @rollcall.update(rollcall_params)
      redirect_to teacher_section_path(@rollcall.event.section), notice: "Attendance record saved."
    else
      flash[:alert] = "Attendance record could not be saved, please try again."
      render :rollcall
    end
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = ::Event.new(section_id: params[:section_id])
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = ::Event.new(event_params)

    if @event.save
      redirect_to teacher_section_path(@event.section), notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to teacher_event_path(@event), notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to :back, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = ::Event.find(params[:id] || params[:event_id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:name, :when, :time, :section_id)
    end

    def rollcall_params
      params.require(:rollcall).permit(:attendance)
    end

    def set_rollcall
      @rollcall = @event.rollcall_or_new
    end
end

app/controllers/teacher/home_controller.rb
class Teacher::HomeController < Teacher::BaseController
  def index
  end
end

app/controllers/teacher/levels_controller.rb
class Teacher::LevelsController < Teacher::BaseController
  def manage
    @levels = Level.all
  end

  def update
    levels = JSON.parse(params["levels"])

    ids = []
    begin
      Level.transaction do
        levels.each do |level_data|
          level_data = level_data.clone

          if id = level_data.delete("id")
            level = Level.find(id)
            level.update!(level_data)
            ids << level.id
          else
            level = Level.create!(level_data)
            ids << level.id
          end
        end
      end

      Level.where('id NOT IN (?)', ids).each do |level|
        level.destroy!
      end
    rescue StandardError => e
      LotteryError.save(e)

      flash.alert = "Could not save changes, please try again."
      @levels = levels.map { |level| Level.new(level) }
      render :manage
      return
    end

    redirect_to [:teacher, :levels], notice: "Changes have been saved."
  end
end

app/controllers/teacher/parents/students_controller.rb
class Teacher::Parents::StudentsController < Teacher::BaseController
  before_action :set_parent

  def index
    @students = @parent.students
  end

  def new
    @student = @parent.students.new
  end

  private
    def set_parent
      @parent = Parent.find(params[:parent_id])
    end

    # Only allow a trusted parameter "white list" through.
    def student_params
      params.fetch(:student, {}).permit(
        :waiver_force,
        :last_name,
        :first_name,
        :birthdate,
        :email,
        :level_id,
        :accommodations,
        :school,
        :school_grade,
        :highest_math_class,
        :priority,
        :waiver_confirmed)
    end
end

app/controllers/teacher/parents_controller.rb
class Teacher::ParentsController < Teacher::BaseController
  before_action :set_parent, only: [:show, :destroy]

  include Searchable
  search :parent_profiles, :profiles

  def index
    @profiles = ParentProfile.order(:first_name, :last_name)
                .paginate(page: params[:page], per_page: 50)
  end

  def destroy
    @parent.destroy
    redirect_to teacher_parents_url, notice: 'Parent was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def parent_params
      params.fetch(:parent, {})
    end
end

app/controllers/teacher/priorities_controller.rb
class Teacher::PrioritiesController < Teacher::BaseController
  before_action :set_threshold
  before_action :set_last_semester

  DEFAULT_THRESHOLD = 4

  def manage
  end

  def reset
    unless @threshold = ensure_int(@threshold)
      flash[:alert] = "Please choose a threshold that is an integer."
      render :manage
      return
    end

    table = Rollcall.attendance_table(@last_semester)

    Student.where("id NOT IN (?)", table.keys)
    .update_all(priority: false)

    table.each do |id, att|
      begin
        Student.find(id).update!(priority: (att >= @threshold))
      rescue ActiveRecord::RecordNotFound => e; end

      # some student's listed in last semester's attendance rolls may have been deleted - that's totally acceptable
    end

    redirect_to teacher_home_path, notice: "Student priorities have been reset."
  end

  private
  def set_threshold
    @threshold = params[:threshold] || DEFAULT_THRESHOLD
  end

  def set_last_semester
    @last_semester = Semester.limit(2).order(start: :desc)[1]

    unless @last_semester
      flash[:alert] = "There is only one semester. In order to reset student priorities, you need to have a past semester."
      render :manage
    end
  end

  def ensure_int str
    Integer(str) rescue false
  end
end

app/controllers/teacher/profiles_controller.rb
class Teacher::ProfilesController < Teacher::BaseController
  before_action :set_parent
  before_action :set_parent_profile

  def show
  end

  def edit
  end

  def update
    if @parent_profile.update(parent_profile_params)
      redirect_to teacher_parents_path, notice: 'Parent profile was successfully updated.'
    else
      render :edit
    end
  end

  private
    def set_parent
      @parent = Parent.find(params[:parent_id])
    end

    def set_parent_profile
      @parent_profile = @parent.profile_or_new
      @profile = @parent_profile
    end

    # Only allow a trusted parameter "white list" through.
    def parent_profile_params
      params.fetch(:parent_profile, {}).permit(:parent_id,
              :first_name, :last_name, :email, :phone,
              :street1, :street2, :city, :state, :zip,
              :ec1_first_name, :ec1_last_name, :ec1_relation, :ec1_phone,
              :ec2_first_name, :ec2_last_name, :ec2_relation, :ec2_phone)
    end
end

app/controllers/teacher/registrees_controller.rb
class Teacher::RegistreesController < Teacher::BaseController
  include RegistreesControllable
  self.role = :teacher
end

app/controllers/teacher/rollcalls_controller.rb
class Teacher::RollcallsController < Teacher::BaseController
  before_action :set_event
  before_action :set_rollcall

  # GET /events/1/rollcall
  def show
  end

  # POST /events/1/rollcall
  def create
    rp = rollcall_params
    @rollcall.attendance   = rp[:attendance]
    @rollcall.unregistered = rp[:unregistered]

    if @rollcall.save
      redirect_to teacher_section_path(@rollcall.event.section), notice: "Attendance record saved."
    else
      flash[:alert] = "Attendance record could not be saved, please try again."
      render :rollcall
    end
  end

  # PATCH/PUT /events/1/rollcall
  def update
    if @rollcall.update(rollcall_params)
      redirect_to teacher_section_path(@rollcall.event.section), notice: "Attendance record saved."
    else
      flash[:alert] = "Attendance record could not be saved, please try again."
      render :rollcall
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = ::Event.find(params[:event_id] || params[:rollcall][:event_id])
    end

    def set_rollcall
      @rollcall = @event.rollcall_or_new
    end

    # Only allow a trusted parameter "white list" through.
    def rollcall_params
      params.fetch(:rollcall, {}).permit(:attendance, :unregistered)
    end
end

app/controllers/teacher/sections_controller.rb
class Teacher::SectionsController < Teacher::BaseController
  before_action :set_section, except: [:new, :create, :index]

  include CsvDownloads

  csv_download :attendance,
    object:   :@section,
    filename: ->(section) { section.attendance_file_name },
    header:   ->(section) { section.attendance_headers   },
    data:     ->(section) { section.attendance_rows      }

  # GET /teacher/events/1
  # GET /teacher/events/1.json
  def show
  end

  # GET /teacher/events/new
  def new
    @section = EventGroup.new(course_id: params[:course_id])
  end

  # GET /teacher/events/1/edit
  def edit
  end

  # POST /teacher/events
  # POST /teacher/events.json
  def create
    @section = EventGroup.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to teacher_course_path(@section.course), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teacher/events/1
  # PATCH/PUT /teacher/events/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to teacher_section_path(@section), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teacher/events/1
  # DELETE /teacher/events/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = EventGroup.find(params[:id] || params[:section_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      sp = params.require(:event_group).permit(:wday, :course_id, :capacity)

      # Previously, we included :event_time above, which cause rails to auto-parse it and interpret it in the current time zone.
      # However, it uses the attached date fields (which is just an empty placeholder) to determine whether to use daylight savings,
      # which leads to times being off-by-one for half the year. We just want to take the raw hour and minute and leave the rest
      sp[:event_time] = Time.zone.local(1, 1, 1, params.require(:event_group)["event_time(4i)"], params.require(:event_group)["event_time(5i)"], 0)

      sp
    end
end

app/helpers/teacher/semesters_helper.rb
module Teacher::SemestersHelper
end

app/views/teacher/sections/_form.html.erb
<%= form_for([:teacher, section]) do |f| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course %>
    <%= f.collection_select :course_id, Course.all, :id, :name, {}, {disabled: :disabled} %>
    <%= f.hidden_field :course_id %>
  </div>

  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </div>

  <% unless section.persisted? %>
    <div class="field">
      <%= f.label :weekday %>
      <%= f.select :wday, DayHelper::DAYS.map { |d| [ d.to_s.titleize, d ] } %>
    </div>

    <div class="field">
      <%= f.label :time %>
      <%= f.time_select :event_time, { ampm: true } %>
    </div>

    <p>
      Submitting this form will create a section that meets on every occurrence of your chosen weekday between the start and end of this semester. You will then be able to add, delete, or reschedule these meetings.
    </p>
  <% end %>

  <div class="actions">
    <%= f.submit (section.persisted? ? "Update section" : "Create section") %>
  </div>
<% end %>

app/views/teacher/sections/_students_panel.html.erb
<div class="card">
  <div class="card-header" role="tab" id="headingOne"><h5 class="mb-0">
    <a data-toggle="collapse" data-parent="#accordion" href="#roster_collapse" aria-expanded="true" aria-controls="collapseOne">Roster</a>
  </h5></div>

  <div id="roster_collapse" class="collapse" role="tabpanel"><div class="card-block">
    <% if section.roster.empty? %>
      No students enrolled.
    <% else %>
      <table>
        <thead><tr><th>Student</th><th>ID</th></tr></thead>
        <tbody><% section.roster.each do |student| %>
          <tr>
            <td><%= link_to student.name, teacher_student_path(student) %></td>
            <td><%= student.id %></td>
          </tr>
        <% end %></tbody>
      </table>
    <% end %>
  </div></div>

  <div class="card-header" role="tab" id="headingOne"><h5 class="mb-0">
    <a data-toggle="collapse" data-parent="#accordion" href="#waitlist_collapse" aria-expanded="true" aria-controls="collapseOne">Waitlist</a>
  </h5></div>

  <div id="waitlist_collapse" class="collapse" role="tabpanel"><div class="card-block">
    <% if section.waitlist.empty? %>
      No students on the waitlist.
    <% else %>
      <table>
        <thead><tr><th></th><th>Student</th><th>ID</th></tr></thead>
        <tbody><% section.waitlist.each_with_index do |registree, i| %>
          <tr>
            <td><%= i + 1 %></td>
            <td><%= link_to registree.student.name, teacher_student_path(registree.student) %></td>
            <td><%= registree.student.id %></td>
          </tr>
        <% end %></tbody>
      </table>
    <% end %>
  </div></div>
</div>

app/views/teacher/sections/edit.html.erb
<h1>Edit event</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', teacher_course_path(@section.course) %>

app/views/teacher/sections/index.html.erb
<h1>Sections</h1>

<!-- TODO: semester selector -->

<%= render partial: 'sections/section_list', locals: { sections: @sections } %>

<br>

<%= link_to 'New Section', new_teacher_section_path %>

app/views/teacher/sections/new.html.erb
<h1>New Section of <%= @section.course.name %></h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', teacher_course_path(@section.course) %>

app/views/teacher/sections/show.html.erb
<h1><%= "#{@section.description}" %></h1>

<p>
  This is a section of
  <%= @section.course.name %>
  during semester
  <%= @section.course.semester.name %>
</p>

<br/>

<%= link_to 'Download attendance record', teacher_section_attendance_path(@section) %>

<br/>

<% if @section.events.any? %>
  <table>
    <thead>
      <tr>
        <th colspan="1">Meeting</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="alternating">
      <% @section.events.each do |event| %>
        <tr>
          <td><%= link_to event.description, teacher_event_path(event) %></td>
          <td><%= link_to 'Attendance', teacher_event_rollcall_path(event) %></td>
          <td><%= link_to 'Edit', edit_teacher_event_path(event) %></td>
          <td><%= link_to 'Delete', teacher_event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  This section does not currently have any meetings scheduled.
  <%= link_to 'Add a new meeting.', new_teacher_section_path(section_id: @section.id) %>
<% end %>

</br></br>

<%= render partial: 'teacher/shared/email_list', locals: { title: "Roster", students: @section.roster } %>

</br></br>

<%= link_to 'New Meeting', new_teacher_event_path(section_id: @section.id) %> |
<%= link_to 'Edit', edit_teacher_section_path(section_id: @section.id) %> |
<%= link_to 'Back', teacher_course_path(@section.course) %>

app/views/teacher/sections/update.html.erb
<h1>Teacher::Events#update</h1>
<p>Find me in app/views/teacher/events/update.html.erb</p>